FIGURA1=figura_1_dispersion_plot_completo
FIGURA2=figura_2_violin_plot_completo
FIGURA3=figura_3_mediciones_aproximadas_vs_ideal
FIGURA4=figura_4_mediciones_aproximadas_vs_ideal_varianza
FIGURA5=figura_5_dist_conjuntas_var_y_cgrupos
FIGURA6=figura_6_pearson_ingreso_consumo_esp_vida_total
FIGURA7=figura_7_pearson_ingreso_consumo_esp_vida_total_bootstrap